---
title: "Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(patchwork)
library(ggridges)
library(viridis)

library(plotly)
```

```{r message=FALSE}
health_data = read_csv("./data/health data.csv") %>% 
  select(-X1) 

city_data = health_data %>% 
  pivot_wider(names_from = measure, city_name, values_from = data_value) %>% 
  unnest() %>% 
  drop_na() %>% 
  group_by(city_name) %>% 
  summarize(obesity = mean(obesity), drink = mean(drink), diabetes = mean(diabetes), mental_health = mean(`mental health`), cancer = mean(cancer),sleeping = mean(sleeping)) %>% 
  pivot_longer(
    obesity:sleeping,
    names_to = "measure",
    values_to = "data_value"
  )
```

Column {data-width=500}
-----------------------------------------------------------------------

###  Obesity conditions in different states

```{r}
state_data_ob = health_data %>%
  filter(measure == "obesity") %>% 
  drop_na(data_value) %>% 
  group_by(state_desc) %>% 
  summarize(state_prevalence = mean(data_value)) %>% 
  filter(state_desc != "United States") %>% 
  mutate(state_desc = fct_reorder(state_desc, state_prevalence))

#draw an interactive bar plot
state_data_ob %>% 
   plot_ly(x = ~state_desc, y = ~state_prevalence, 
          color = ~state_desc, type = "bar") %>% 
  layout(
    title = "Prevalence of Obesity in States",
    xaxis = list(title = "States"),
    yaxis = list(title = "Crude Prevenlence (%)"),
    margin = list(b = 170)
  )
```

###  Diabetes conditions in different states

```{r}
state_data_dia = health_data %>%
  filter(measure == "diabetes") %>% 
  drop_na(data_value) %>%
  select(data_value,state_desc,measure) %>% 
  group_by(state_desc) %>% 
  filter(state_desc != "United States") 

#draw an interactive bar plot
state_data_dia %>% 
   plot_ly( y = ~data_value, 
          color = ~state_desc, type = "box") %>% 
  layout(
    title = "Prevalence of Diabetes in States",
    xaxis = list(title = "States"),
    yaxis = list(title = "Crude Prevenlence (%)"),
    margin = list(b = 170)
  )

```


Column {data-width=500}
-----------------------------------------------------------------------

### Drinking conditions in different cities

```{r}
drink_data = health_data %>%
  filter(measure == "drink",state_desc != "United States") %>% 
  extract(geo_location, c("Latitude", "Longitude"), "\\(([^,]+), ([^)]+)\\)") %>% 
  janitor::clean_names() %>% 
  select(city_name, latitude, longitude, data_value, measure) %>% 
  group_by(city_name) %>% 
  drop_na(data_value) %>% 
  mutate(m_data_value = mean(data_value)) %>% 
  distinct() %>% 
  mutate(latitude = as.integer(latitude),
         longitude = as.integer(longitude)) %>% 
  mutate(text_label = str_c("Prevalence(%):", m_data_value)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, 
          color = ~m_data_value, type = "scatter", 
          mode = "markers", text = ~text_label,alpha = .5) %>%
  layout(
    title = "Prevalence of Binge Drinking in United States",
    xaxis = list(title = "Longitude"),
    yaxis = list(title = "Latitude")
  )
    
 
drink_data
```

### Cancer conditions in different cities

```{r}
cancer_data = health_data %>%
  filter(measure == "cancer",state_desc != "United States") %>% 
  extract(geo_location, c("Latitude", "Longitude"), "\\(([^,]+), ([^)]+)\\)") %>% 
  janitor::clean_names() %>% 
  select(city_name,latitude, longitude, data_value, measure) %>% 
  group_by(city_name) %>% 
  drop_na(data_value) %>% 
  mutate(m_data_value = mean(data_value)) %>% 
  distinct() %>% 
  mutate(latitude = as.integer(latitude),
         longitude = as.integer(longitude)) %>% 
  mutate(text_label = str_c("Prevalence(%):", m_data_value)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, 
          color = ~m_data_value, type = "scatter", 
          mode = "markers",text = ~text_label,alpha = .5) %>%
  layout(
    title = "Prevalence of Cancer in United States",
    xaxis = list(title = "Longitude"),
    yaxis = list(title = "Latitude")
  )
    
 
cancer_data
```

### Sleeping conditions in different cities

```{r}
sleep_data = health_data %>%
  filter(measure == "sleeping",state_desc != "United States") %>% 
  extract(geo_location, c("Latitude", "Longitude"), "\\(([^,]+), ([^)]+)\\)") %>% 
  janitor::clean_names() %>% 
  select(city_name,latitude, longitude, data_value, measure) %>% 
  group_by(city_name) %>% 
  drop_na(data_value) %>% 
  mutate(m_data_value = mean(data_value)) %>% 
  distinct() %>% 
  mutate(latitude = as.integer(latitude),
         longitude = as.integer(longitude)) %>% 
  mutate(text_label = str_c("Prevalence(%):", m_data_value)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, 
          color = ~m_data_value, type = "scatter", 
          mode = "markers", text = ~text_label,alpha = .5) %>%
  layout(
    title = "Condition of Sleeping in United States",
    xaxis = list(title = "Longitude"),
    yaxis = list(title = "Latitude")
  )
    
 
sleep_data 
```

