---
title: "Proposal_document"
author: "YucongJiang, WeiRan Zhang, Qi Lu, Yuning Wang, Aiming Liu"
date: "2019-11-4"
output: github_document
---


## Group Members

* Yucong Jiang (yj2581)

* WeiRan Zhang (wz2506)

* Qi Lu (ql2370)

* Yuning Wang (yw3438)

* Aiming Liu (al3998)

## Tentative Project Title
 
 *Mental health conditions in the United states*

## Motivation for This Project
  
  Mental illnesses are conditions that affect a person’s thinking, feeling, mood or behavior, such as depression, anxiety or bipolar disorder.  
  
  Mental health is an important component of overall health.Mental health problems can increases the risk for many types of physical health problems,for example diabetes,cancer,obesity,heart disease and so on. Similarly, the presence of chronic physical health problems can also increase the risk for mental health problems.

## Intended Final Products

 + Website with visulization showing statistical analysis
 
    - Statistical plots
  
    - Interactive map(s)
  
    - Statistical table(s)

 + Screencast to introduce the project

## Anticipated Data Sources

[500 Cities: Local Data for Better Health, 2018 release](https://chronicdata.cdc.gov/500-Cities/500-Cities-Local-Data-for-Better-Health-2018-relea/6vp6-wxuq/data). Relevant parameters were selected to create our own dataset with only relevant variables.

## Planned Analyses / Visualizations / Coding Challenges

**Planned analysis & Visualizations**

 + We plan to analysis the geographic distribution of mental health problem in U.S. and use statistical models to detect the potential risk factors associated with mental health problem.

**Coding Challenges**
 
 + The challenge is more related to finding out the correct relevant variables in the large dataset and using correct statistical models to analysis association between mental health and other variables.


## The planned time line

* Week 0 (Nov 7 - 13): 
    + Writing proposal after review meeting 
    + Finding enough data sources
  
* Week 1 (Nov 14 - 20):
    + Data exploration and analyses
  
* Week 2 (Nov 21 - 27):
    + Data visualizations and conclusions
    
* Week 3 (Nov 28 - Dec 4):
    + Report, website and screencast




